version: '3'
services:
  go:
    image: golang:1.15
    container_name: gotodoapi
    volumes:
      - .:/todoAPI
    working_dir: /todoAPI
    command: > 
      bash -c "go build -o ./bin/app main.go
      && echo 'build ready' && ./bin/app"
    links:
      - postgres
    ports:
      - 8080:8080
  postgres:
    image: postgres
    container_name: postgrestodo
    restart: always
    environment:
      POSTGRES_DB: todogolang
      POSTGES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/postgres
